engines:
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - app/views/**/*
    config:
      languages:
        ruby:
          mass_threshold: 20
style_guide: beatrizChagas/linter
exclude_paths:
- lib/generators/**/*.tt
- config
- test
